# Generated by Django 5.0.7 on 2024-08-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
    ]
