# Generated by Django 5.0.7 on 2024-07-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
