# Generated by Django 5.0.7 on 2024-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_employed',
            field=models.BooleanField(default=True),
        ),
    ]
