# Generated by Django 5.0.7 on 2024-07-28 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_is_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='mobile_number',
            field=models.CharField(default='8793798679', max_length=10,),
        ),
    ]
