# Generated by Django 5.0.7 on 2024-07-28 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
