# Generated by Django 5.0.7 on 2024-07-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driver_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='mobile_number',
        ),
    ]
