# Generated by Django 5.0.7 on 2024-07-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_alter_driver_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_employed',
        ),
    ]
