# Generated by Django 5.0.7 on 2024-08-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_alter_driver_owner_alter_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='experience_years',
        ),
    ]
