# Generated by Django 5.0.7 on 2024-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='journey_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='journey_type',
            field=models.CharField(blank=True, choices=[('One Way', 'One Way'), ('Two Way', 'Two Way'), ('Local', 'Local'), ('Multiple Locations', 'Multiple Locations')], max_length=20, null=True),
        ),
    ]
