# Generated by Django 5.0.7 on 2024-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_drop_city_booking_drop_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_type',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Two Way', 'Two Way'), ('Local', 'Local'), ('Multiple Locations', 'Multiple Locations')], max_length=20),
        ),
    ]
