# Generated by Django 5.0.7 on 2024-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_journey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
