# Generated by Django 5.0.7 on 2024-07-30 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_total_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
