# Generated by Django 5.0.7 on 2024-07-31 04:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_customer_phone'),
        ('owners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings',
                                    to='owners.owner'),
            preserve_default=False,
        ),
    ]
