# Generated by Django 5.0.7 on 2024-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_booking_multi_drops_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_charges',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_city',
            field=models.CharField(max_length=30),
        ),
    ]
