# Generated by Django 5.0.7 on 2024-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_additional_charges_alter_booking_drop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey_type',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Two Way', 'Two Way'), ('Local', 'Local'), ('Multiple Locations', 'Multiple Locations')], max_length=200),
        ),
    ]
